version: "3.8"

services:
  #TODO: Spring boot app
  springmovieapp:
    container_name: springmovieapp
    image: springmovieapp
    build: .
    ports:
      - 8080:8080
    environment:
      # - DATABASE_URL=jdbc:mysql://mysql-movie-container:3306/ticketbookingmovie_db?allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=thanhdu
      - DATABASE_PASSWORD=password
      - JWT_SECRET_KEY=================================================================
      - JWT_EXPIRATION=86400000
      - ACCESS_KEY_ID=
      - SECRET_ACCESS_KEY=
      - REGION=
      - S3_BUCKET_NAME_MOVIE=
      - EMAIL_PORT=587
      - EMAIL=
      - PASSEMAIL=
      - REDIS_HOST=
      - REDIS_PORT=12179
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=
