name: Deploy to AWS ECS
on:
  push:
    branches: [master]
permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker-compose build
      - name: Tag Docker image
        run: docker tag springmovieapp thanh369/springmovieapp
      - name: Push Docker image to Docker Hub
        run: docker push thanh369/springmovieapp
  deploy:
    needs: build
    runs-on: [springmovie-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull thanh369/springmovieappp
      - name: Delete old container
        run: docker rm -f springmovieapp
      - name: Run new container
        run: docker run -d -p 8080:8080 --name springmovieapp thanh369/springmovieapp
